### PR TITLE
Link to party detail

### PR DESCRIPTION
**Pull request by kimberlytze**
Makes the Party Search Results and See All pages more useful by linking to the respective party detail page using the new custom urls

@VOjha @vsiri

### CODE REVIEW

**Comment by VOjha** [comment]
Nice :D Could you add a screenshot? I just want to see how the colors work lol

**Comment by kimberlytze** [comment]
@VOjha 

screen shot 2016-07-27 at 10 14 15 am

**Comment by kimberlytze** [comment]
Mouse is hovering over the last one

**Comment by VOjha** [comment]
Oh interesting. Can we do the traditional underline thing to make it clear that they're links? And I feel like just the name of the party (not the ", by person" part) should be a link... thoughts?

**Comment by kimberlytze** [comment]
screen shot 2016-07-27 at 10 22 16 am

Here's how it looks underlined, except on hover.

**Comment by kimberlytze** [comment]
I like having the whole thing as a link. @vsiri ?

**Comment by vsiri** [comment]
@kimberlytze @VOjha I like the whole thing as a link but the underline is good.. but i feel like it could be prettier BUT IDK HOW

**Comment by kimberlytze** [comment]
We'll deal with prettiness later.. LOL

**Comment by VOjha** [comment]
Ooh maybe we could let people pick photos to be like their party icons or something????

**Comment by VOjha** [comment]
But yeah wooo :ship: :D :D

**Comment by kimberlytze** [comment]
^ i was just about to say that
banana-cheerleader

**Pull request closed without merging**
