### PR TITLE
Delete Track

### PR DESCRIPTION
**Pull request by VOjha**
Issue #57 

Adds a `Remove` column on the Party detail page, so a song can be removed (from Spotify and the DB). It doesn't look particularly stunning but there it is.

screen shot 2016-08-01 at 2 21 29 pm

@vsiri @kimberlytze

### CODE REVIEW

**Comment by vsiri** [comment]
try .glyphicon.glyphicon-trash instead of the btn! then we shouldnt need the remove since it'll be self explanatory??? maybe? or we should figure out how to center it

**Comment by vsiri** [comment]
and you can try the trashcan with our off-white or an error-red-color

**Comment by VOjha** [comment]
screen shot 2016-08-01 at 3 42 43 pm

Changed it to the trash icon. I think the icon could be outside of the playlist (outside of the purple box that encases the playlist). What do you guys think? @vsiri @kimberlytze

**Comment by VOjha** [comment]
I'm going to ship this for now and we can make it prettier later.

**Pull request closed without merging**
