### PR TITLE
Vs/admin button

### PR DESCRIPTION
**Pull request by vsiri**
welp i was supposed to type meh for the tokens commit but i accidentally did it for all commits

this adds the admin button

@VOjha @kimberlytze

### CODE REVIEW

**Comment by VOjha** [comment]
Screenshot? 😇

**Comment by vsiri** [comment]
y dont u visit me at my branch :[
screen shot 2016-08-05 at 2 03 50 pm

**Comment by VOjha** [comment]
Lol you mean type
`git checkout vs/admin-button`
`python manage.py runserver`
and then 
`127.0.0.1:8000`
r u srs 2 much effort

**Comment by VOjha** [comment]
:ship:

**Comment by vsiri** [comment]
gotta raise ur wpm @VOjha

**Comment by vsiri** [comment]
practice makes perf

**Pull request closed without merging**
