### PR TITLE
fix underline and spacing

### PR DESCRIPTION
**Pull request by vsiri**
screen shot 2016-08-03 at 11 29 25 am

@VOjha @kimberlytze

### CODE REVIEW

**Comment by VOjha** [comment]
Hmm I don't know if I'm a huge fan of the text being indented away from the boxes like that. Everything else (header and boxes) are along the same line and they just stick out too much, IMO.

**Comment by vsiri** [comment]
@VOjha 
screen shot 2016-08-03 at 1 42 30 pm

**Comment by kimberlytze** [comment]
🐑

**Comment by VOjha** [comment]
Yay ty :rocket:

**Pull request closed without merging**
