### PR TITLE
Remove scoped to user

### PR DESCRIPTION
**Pull request by kimberlytze**
Issue #73 

Tracks now keep track(lol) of which user added the song, so the remove button for that track only appears for that user.

image

@VOjha @vsiri

### CODE REVIEW

**Comment by VOjha** [comment]
IMO we should call this attribute something more descriptive than `username`. I was going to call it `added_by`, what do you think?

**Comment by VOjha** [comment]
Also lol how did you test this with different accounts? Do you casually have multiple Spotify accounts lol

**Comment by kimberlytze** [comment]
`added_by` sounds good to me :p
And I used the up--next Spotify account to test lol

**Comment by VOjha** [comment]
Oh nice genius :+1:

I mean, naisu :P

**Comment by VOjha** [comment]
Yay! Nice :D :shipit:

**Comment by vsiri** [comment]
🐑

**Pull request closed without merging**
