### PR TITLE
Add search bar to search results page

### PR DESCRIPTION
**Pull request by kimberlytze**
Issue #28 

screen shot 2016-07-25 at 3 30 25 pm

@VOjha @vsiri

### CODE REVIEW

**Comment by VOjha** [comment]
Wait, maybe I'm confused... so right now a search bar appears on the page, but doesn't do anything, right? Because you don't have any code in `views.py` that actually handles the search query, as far as I can tell?

**Comment by kimberlytze** [comment]
@VOjha It works! I think it's cuz the url is still `/party/...`, so `party_detail` in `view.py` is actually being called

**Comment by vsiri** [comment]
👍

**Comment by VOjha** [comment]
OHHH I see. That's interesting. Do we want that to happen? Like, should the search results be on their own URL, or be the party's URL with additions... ? I'm ok with it as it is, especially since it made the addition of this search bar so much easier lol

**Comment by VOjha** [comment]
Oh and also :shipit:

**Pull request closed without merging**
